from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.depremparametre_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.depremparametre_groupbox.setGeometry(QtCore.QRect(30, 30, 911, 211))
        self.depremparametre_groupbox.setObjectName("depremparametre_groupbox")
        self.tasiyicisistemx_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.tasiyicisistemx_lnEdit.setGeometry(QtCore.QRect(210, 30, 91, 20))
        self.tasiyicisistemx_lnEdit.setObjectName("tasiyicisistemx_lnEdit")
        self.tasiyicisistemy_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.tasiyicisistemy_lnEdit.setGeometry(QtCore.QRect(210, 60, 91, 20))
        self.tasiyicisistemy_lnEdit.setObjectName("tasiyicisistemy_lnEdit")
        self.binaonem_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.binaonem_lbl.setGeometry(QtCore.QRect(310, 120, 101, 16))
        self.binaonem_lbl.setObjectName("binaonem_lbl")
        self.binaonem_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.binaonem_lnEdit.setGeometry(QtCore.QRect(450, 120, 101, 20))
        self.binaonem_lnEdit.setObjectName("binaonem_lnEdit")
        self.kappa_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.kappa_lbl.setGeometry(QtCore.QRect(560, 120, 111, 16))
        self.kappa_lbl.setObjectName("kappa_lbl")
        self.kappa_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.kappa_lnEdit.setGeometry(QtCore.QRect(680, 120, 101, 20))
        self.kappa_lnEdit.setObjectName("kappa_lnEdit")
        self.tx_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.tx_lbl.setGeometry(QtCore.QRect(310, 30, 131, 16))
        self.tx_lbl.setObjectName("tx_lbl")
        self.tx_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.tx_lnEdit.setGeometry(QtCore.QRect(450, 30, 101, 20))
        self.tx_lnEdit.setObjectName("tx_lnEdit")
        self.ty_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.ty_lbl.setGeometry(QtCore.QRect(310, 60, 131, 16))
        self.ty_lbl.setObjectName("ty_lbl")
        self.ty_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.ty_lnEdit.setGeometry(QtCore.QRect(450, 60, 101, 20))
        self.ty_lnEdit.setObjectName("ty_lnEdit")
        self.esnekduvarderzi_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.esnekduvarderzi_lbl.setGeometry(QtCore.QRect(20, 90, 181, 16))
        self.esnekduvarderzi_lbl.setObjectName("esnekduvarderzi_lbl")
        self.esnekduvarderzi_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.esnekduvarderzi_lnEdit.setGeometry(QtCore.QRect(210, 90, 91, 20))
        self.esnekduvarderzi_lnEdit.setObjectName("esnekduvarderzi_lnEdit")
        self.dogaltitresim_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.dogaltitresim_lbl.setGeometry(QtCore.QRect(310, 90, 141, 16))
        self.dogaltitresim_lbl.setObjectName("dogaltitresim_lbl")
        self.dogaltitresim_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.dogaltitresim_lnEdit.setGeometry(QtCore.QRect(450, 90, 101, 20))
        self.dogaltitresim_lnEdit.setObjectName("dogaltitresim_lnEdit")
        self.hi_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.hi_lbl.setGeometry(QtCore.QRect(560, 90, 111, 16))
        self.hi_lbl.setObjectName("hi_lbl")
        self.hi_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.hi_lnEdit.setGeometry(QtCore.QRect(680, 90, 101, 20))
        self.hi_lnEdit.setObjectName("hi_lnEdit")
        self.celiktekkatli_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.celiktekkatli_lbl.setGeometry(QtCore.QRect(20, 120, 151, 16))
        self.celiktekkatli_lbl.setObjectName("celiktekkatli_lbl")
        self.celiktekkatli_cmbBox = QtWidgets.QComboBox(self.depremparametre_groupbox)
        self.celiktekkatli_cmbBox.setGeometry(QtCore.QRect(210, 120, 91, 22))
        self.celiktekkatli_cmbBox.setObjectName("celiktekkatli_cmbBox")
        self.celiktekkatli_cmbBox.addItem("")
        self.celiktekkatli_cmbBox.addItem("")
        self.xdeplasman_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.xdeplasman_lbl.setGeometry(QtCore.QRect(560, 30, 121, 16))
        self.xdeplasman_lbl.setObjectName("xdeplasman_lbl")
        self.ydeplasman_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.ydeplasman_lbl.setGeometry(QtCore.QRect(560, 60, 121, 16))
        self.ydeplasman_lbl.setObjectName("ydeplasman_lbl")
        self.xdeplasman_lnEdit = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.xdeplasman_lnEdit.setGeometry(QtCore.QRect(680, 30, 101, 20))
        self.xdeplasman_lnEdit.setObjectName("xdeplasman_lnEdit")
        self.xdeplasman_lnEdit_2 = QtWidgets.QLineEdit(self.depremparametre_groupbox)
        self.xdeplasman_lnEdit_2.setGeometry(QtCore.QRect(680, 60, 101, 20))
        self.xdeplasman_lnEdit_2.setObjectName("xdeplasman_lnEdit_2")
        self.ctkatsayisi_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.ctkatsayisi_lbl.setGeometry(QtCore.QRect(20, 150, 71, 16))
        self.ctkatsayisi_lbl.setObjectName("ctkatsayisi_lbl")
        self.ctkatsayisi_cmBox = QtWidgets.QComboBox(self.depremparametre_groupbox)
        self.ctkatsayisi_cmBox.setGeometry(QtCore.QRect(210, 150, 91, 22))
        self.ctkatsayisi_cmBox.setObjectName("ctkatsayisi_cmBox")
        self.ctkatsayisi_cmBox.addItem("")
        self.ctkatsayisi_cmBox.addItem("")
        self.ctkatsayisi_cmBox.addItem("")
        self.tasiyicisistemx_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.tasiyicisistemx_lbl.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.tasiyicisistemx_lbl.setObjectName("tasiyicisistemx_lbl")
        self.tasiyicisistemy_lbl = QtWidgets.QLabel(self.depremparametre_groupbox)
        self.tasiyicisistemy_lbl.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.tasiyicisistemy_lbl.setObjectName("tasiyicisistemy_lbl")
        self.tasiyicisistemx_lnEdit.raise_()
        self.binaonem_lbl.raise_()
        self.binaonem_lnEdit.raise_()
        self.kappa_lbl.raise_()
        self.kappa_lnEdit.raise_()
        self.tx_lbl.raise_()
        self.tx_lnEdit.raise_()
        self.ty_lbl.raise_()
        self.ty_lnEdit.raise_()
        self.esnekduvarderzi_lbl.raise_()
        self.esnekduvarderzi_lnEdit.raise_()
        self.dogaltitresim_lbl.raise_()
        self.dogaltitresim_lnEdit.raise_()
        self.hi_lbl.raise_()
        self.hi_lnEdit.raise_()
        self.celiktekkatli_lbl.raise_()
        self.celiktekkatli_cmbBox.raise_()
        self.xdeplasman_lbl.raise_()
        self.ydeplasman_lbl.raise_()
        self.xdeplasman_lnEdit.raise_()
        self.xdeplasman_lnEdit_2.raise_()
        self.ctkatsayisi_lbl.raise_()
        self.ctkatsayisi_cmBox.raise_()
        self.tasiyicisistemx_lbl.raise_()
        self.tasiyicisistemy_lbl.raise_()
        self.tasiyicisistemy_lnEdit.raise_()
        self.dd2_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.dd2_groupbox.setGeometry(QtCore.QRect(30, 250, 131, 81))
        self.dd2_groupbox.setObjectName("dd2_groupbox")
        self.sds_dd2_lnEdit = QtWidgets.QLineEdit(self.dd2_groupbox)
        self.sds_dd2_lnEdit.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.sds_dd2_lnEdit.setObjectName("sds_dd2_lnEdit")
        self.sd1_dd2_lnEdit = QtWidgets.QLineEdit(self.dd2_groupbox)
        self.sd1_dd2_lnEdit.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.sd1_dd2_lnEdit.setObjectName("sd1_dd2_lnEdit")
        self.dd3_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.dd3_groupbox.setGeometry(QtCore.QRect(180, 250, 131, 81))
        self.dd3_groupbox.setObjectName("dd3_groupbox")
        self.sds_dd3_lnEdit = QtWidgets.QLineEdit(self.dd3_groupbox)
        self.sds_dd3_lnEdit.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.sds_dd3_lnEdit.setObjectName("sds_dd3_lnEdit")
        self.sd1_dd3_lnEdit = QtWidgets.QLineEdit(self.dd3_groupbox)
        self.sd1_dd3_lnEdit.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.sd1_dd3_lnEdit.setObjectName("sd1_dd3_lnEdit")
        self.kaydet_pshbttn = QtWidgets.QPushButton(self.centralwidget)
        self.kaydet_pshbttn.setGeometry(QtCore.QRect(350, 250, 71, 21))
        self.kaydet_pshbttn.setObjectName("kaydet_pshbttn")
        self.check_pshbttn = QtWidgets.QPushButton(self.centralwidget)
        self.check_pshbttn.setGeometry(QtCore.QRect(430, 310, 71, 21))
        self.check_pshbttn.setObjectName("check_pshbttn")
        self.celik_pshbttn = QtWidgets.QComboBox(self.centralwidget)
        self.celik_pshbttn.setGeometry(QtCore.QRect(430, 280, 101, 22))
        self.celik_pshbttn.setObjectName("celik_pshbttn")
        self.celik_pshbttn.addItem("")
        self.celik_pshbttn.addItem("")
        self.deger_pshbttn = QtWidgets.QComboBox(self.centralwidget)
        self.deger_pshbttn.setGeometry(QtCore.QRect(350, 280, 71, 22))
        self.deger_pshbttn.setObjectName("deger_pshbttn")
        self.deger_pshbttn.addItem("")
        self.deger_pshbttn.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Göreli Kat Ötelemesi Kontrolü"))
        self.depremparametre_groupbox.setTitle(_translate("MainWindow", "Deprem Parametreleri"))
        self.binaonem_lbl.setText(_translate("MainWindow", "Bina Önem Katsayısı:"))
        self.kappa_lbl.setText(_translate("MainWindow", "Kappa "))
        self.kappa_lnEdit.setPlaceholderText(_translate("MainWindow","κ"))
        self.tx_lbl.setText(_translate("MainWindow", "X yönü Tepe Periyodu"))
        self.tx_lnEdit.setPlaceholderText(_translate("MainWindow","Tx"))
        self.ty_lbl.setText(_translate("MainWindow", "Y yönü Tepe Periyodu"))
        self.ty_lnEdit.setPlaceholderText(_translate("MainWindow","Ty"))
        self.esnekduvarderzi_lbl.setText(_translate("MainWindow", "Esnek Duvar Derzi"))
        self.dogaltitresim_lbl.setText(_translate("MainWindow", "Doğal Titreşim Periyodu"))
        self.dogaltitresim_lnEdit.setPlaceholderText(_translate("MainWindow","Tpa"))
        self.hi_lbl.setText(_translate("MainWindow", "i\'inci katın yüksekliği"))
        self.hi_lnEdit.setPlaceholderText(_translate("MainWindow","hi"))
        self.celiktekkatli_lbl.setText(_translate("MainWindow", "Çelik Çerçeve ve Tek katlı yapı"))
        self.celiktekkatli_cmbBox.setItemText(0, _translate("MainWindow", "Evet"))
        self.celiktekkatli_cmbBox.setItemText(1, _translate("MainWindow", "Hayır"))
        self.xdeplasman_lbl.setText(_translate("MainWindow", "X yönü deplasmanı"))
        self.ydeplasman_lbl.setText(_translate("MainWindow", "y yönü deplasmanı"))
        self.ctkatsayisi_lbl.setText(_translate("MainWindow", "Ct Katsayısı"))
        self.ctkatsayisi_cmBox.setItemText(0, _translate("MainWindow", "0.1"))
        self.ctkatsayisi_cmBox.setItemText(1, _translate("MainWindow", "0.08"))
        self.ctkatsayisi_cmBox.setItemText(2, _translate("MainWindow", "0.07"))
        self.tasiyicisistemx_lbl.setText(_translate("MainWindow", "Taşıyıcı Sistem Davranışı Katsayısı, X"))
        self.tasiyicisistemx_lnEdit.setPlaceholderText(_translate("MainWindow","R_X"))        
        self.tasiyicisistemy_lbl.setText(_translate("MainWindow", "Taşıyıcı Sistem Davranışı Katsayısı, Y"))
        self.tasiyicisistemy_lnEdit.setPlaceholderText(_translate("MainWindow","R_Y"))        
        self.dd2_groupbox.setTitle(_translate("MainWindow", "DD-2 Parametreleri"))
        self.sds_dd2_lnEdit.setPlaceholderText(_translate("MainWindow","SDS for DD2"))
        self.sd1_dd2_lnEdit.setPlaceholderText(_translate("MainWindow","SD1 for DD2"))
        self.dd3_groupbox.setTitle(_translate("MainWindow", "DD-3 Parametreleri"))
        self.sds_dd3_lnEdit.setPlaceholderText(_translate("MainWindow","SDS for DD3"))
        self.sd1_dd3_lnEdit.setPlaceholderText(_translate("MainWindow","SD1 for DD3"))
        self.kaydet_pshbttn.setText(_translate("MainWindow", "Kaydet"))
        self.check_pshbttn.setText(_translate("MainWindow", "Check"))
        self.celik_pshbttn.setItemText(0, _translate("MainWindow", "Çelik, κ = 0.5"))
        self.celik_pshbttn.setItemText(1, _translate("MainWindow", "Betonarme, κ=1"))
        self.deger_pshbttn.setItemText(0, _translate("MainWindow", "0.008 κ"))
        self.deger_pshbttn.setItemText(1, _translate("MainWindow", "0.016 κ"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
